### ISSUE TITLE
Error in x$theme : $ operator not defined for this S4 class

### ISSUE THREAD

**Issue by apulvino** [tidymass/massqc#1]
**I get the error in the title when running the basic command for massqc_report:**
massqc::massqc_report(object = object_pos, 
                      path = "/path/to/positive_scans/data_quality_before_data_cleaning")

**The full error is as follows:**
Get report template.
Warning: cannot rename file '/path/to/positive_scans/data_quality_before_data_cleaning/Report/skeleton.Rmd' to '/path/to/positive_scans/data_quality_before_data_cleaning/positive_scans/data_quality_before_data_cleaning/Report/Report.Rmd', reason 'No such file or directory'Parameters.
Sample infromation.
Error in x$theme : $ operator not defined for this S4 class

**Comment by apulvino** [comment]
I'm able to reproduce the error by running the template commands here:
https://massqc.tidymass.org/articles/html_qa_report.html

Get report template.
Warning: cannot rename file 'demo_data/Report/skeleton.Rmd' to 'demo_data/Report/Report.Rmd', reason 'No such file or directory'Parameters.
Sample infromation.
Error in x$theme : $ operator not defined for this S4 class

**Comment by jaspershen** [comment]
It is weird. Could you share the object and code you used? My email is shenxt@stanford.edu

**Comment by apulvino** [comment]
I believe this was a dependency/versioning issue I was running into last week, but it has since been resolved. Thanks for your reply, and apologies for any inconvenience!

**Comment by jaspershen** [comment]
Great!
